sudo: false
language: c

cache:
  directories:
    - $HOME/.gcc-arm-embedded
    - $HOME/.stack

addons:
  apt:
    packages:
      - gcc-multilib

matrix:
  include:
    - env: GHCVER=7.10.3 STACK_YAML=stack.yaml
      addons: {apt: {packages: [ghc-7.10.3,gcc-multilib], sources: [hvr-ghc]}}
    - env: GHCVER=8.0.2 STACK_YAML=stack-8.0.2.yaml
      addons: {apt: {packages: [ghc-8.0.2,gcc-multilib], sources: [hvr-ghc]}}

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  # Set up the ARM GCC toolchain
  - if [ ! -d $HOME/.gcc-arm-embedded/*/bin ];
    then
      mkdir -p $HOME/.gcc-arm-embedded;
      wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2 -O- | tar xjf - -C $HOME/.gcc-arm-embedded;
    fi
  - echo $HOME/.gcc-arm-embedded/*/bin
  - ls $HOME/.gcc-arm-embedded/*/bin
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
  - ghc --version
  - export PATH="$(echo $HOME/.gcc-arm-embedded/*/bin):$PATH"
  - arm-none-eabi-gcc --version

install:
  # Check out depenendency repos, then check out the branch that
  # matches the current branch name in this repo. If one doesn't
  # exist, don't fail, in case we're branched in this repo but just
  # depending on master elsewhere.
  #
  # Travis seems to have no problem with the multi-line if above,
  # but barfs when we format this one nicely.
  - for repo in ivory tower; do git clone https://github.com/galoisinc/$repo; (cd $repo; git checkout $TRAVIS_BRANCH) || true; export $(echo ${repo^^} | tr - _)_REPO=$PWD/$repo; done
  # tweak the relative paths in stack.yaml
  - export STACK_YAML=$PWD/$STACK_YAML
  - sed -i "s;\.\./;$PWD/;g" $STACK_YAML

script:
- make travis-test
