$(call add-cabal-package-source, \
  $(BSP_REPO)/ivory-bsp-stm32 \
  $(BSP_REPO)/ivory-freertos-bindings \
  $(IVORY_REPO)/ivory \
  $(IVORY_REPO)/ivory-artifact \
  $(IVORY_REPO)/ivory-backend-c \
  $(IVORY_REPO)/ivory-hw \
  $(IVORY_REPO)/ivory-stdlib \
  $(TOWER_REPO)/tower \
  $(TOWER_REPO)/tower-config \
)
