$(call add-cabal-package-source, \
  $(IVORY_REPO)/ivory \
  $(IVORY_REPO)/ivory-artifact \
  $(IVORY_REPO)/ivory-hw \
  $(IVORY_REPO)/ivory-stdlib \
  $(TOWER_REPO)/tower \
  $(TOWER_REPO)/tower-config \
  $(TOWER_REPO)/tower-hal \
)
