$(call add-cabal-package-source, \
  $(BSP_REPO)/ivory-bsp-stm32 \
  $(BSP_REPO)/tower-freertos-stm32 \
  $(IVORY_REPO)/ivory \
  $(IVORY_REPO)/ivory-hw \
  $(IVORY_REPO)/ivory-stdlib \
  $(TOWER_REPO)/tower \
  $(TOWER_REPO)/tower-config \
  $(TOWER_REPO)/tower-hal \
)
