$(call add-cabal-package-source, \
  $(IVORY_REPO)/ivory \
  $(IVORY_REPO)/ivory-artifact \
  $(IVORY_REPO)/ivory-backend-c \
  $(TOWER_REPO)/tower \
  $(TOWER_REPO)/tower-config \
	$(TOWER_REPO)/tower-aadl \
  $(BSP_REPO)/ivory-bsp-stm32 \
)
